public enum CallType {
    CREATE_PROCESS, SWITCH_PROCESS, INIT_CREATE, SLEEP, OPEN, CLOSE, READ, SEEK, WRITE, GET_PID, SEND_MESSAGE, WAIT_FOR_MESSAGE, GET_PID_BY_NAME, GET_MAPPING, ALLOCATE_MEM, FREE_MEM
}
